### ISSUE TITLE
Pulumi windows32 is not supported

### ISSUE THREAD

**Issue by MitkoTschimev** [Dev-Thought/pulumi-npm#6]
**Describe the bug**
Unfortunately, your platform and architecture (win32, x64) isn't currently supported by Pulumi. Please uninstall this package.

**To Reproduce**
Install on Windows 10

**Expected behavior**
successful installation

**Logs**
npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! @dev-thought/pulumi-npm@1.5.0 postinstall: node src/install-pulumi
npm ERR! Exit status 10
npm ERR!
npm ERR! Failed at the @dev-thought/pulumi-npm@1.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Additional context**
Pulumi supports Win 10.

**Comment by MitkoTschimev** [comment]
Fixed with version 1.5.1

**Comment by zdenekmikel** [comment]
Hi, thanks for fixing the bug but i have another problem.

An unhandled exception occurred: An error occurred while unpacking: Error: Unexpected end of data.
npm ERR! code ELIFECYCLE
npm ERR! errno 40
npm ERR! @dev-thought/pulumi-npm@1.5.1 postinstall: `node src/install-pulumi`
npm ERR! Exit status 40
npm ERR! 
npm ERR! Failed at the @dev-thought/pulumi-npm@1.5.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by MitkoTschimev** [comment]
have you been able to see the download of the archive?

**Comment by zdenekmikel** [comment]
Downloading zipped Pulumi executable from https://get.pulumi.com/releases/sdk/pulumi-v2.15.6-windows-x64.tar.gz...
C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\progress\lib\node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);


RangeError: Invalid array length
    at ProgressBar.render (C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\progress\lib\node-progress.js:160:14)
    at ProgressBar.tick (C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\progress\lib\node-progress.js:97:8)
    at IncomingMessage.<anonymous> (C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\@dev-thought\pulumi-npm\src\install-pulumi\download.js:25:40)
    at IncomingMessage.emit (events.js:200:13)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:977:34)
    at resume_ (_stream_readable.js:958:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by MitkoTschimev** [comment]
Okay, so it looks for me that the lib which shows the download's progress bar somehow is not working with windows. I will try to find any issue and if a replacement with another one is possible or maybe for windows to deactivate it.

**Comment by MitkoTschimev** [comment]
Can you try to update the plugin which should install version 1.5.2 of pulumi-npm

Check the package-lock.json that the newest version is installed.
After the verification please try again. You should see that the progress bar is not supported by the system but the download still works in the background ;)

**Comment by zdenekmikel** [comment]
> node src/install-pulumi

Downloading zipped Pulumi executable from https://get.pulumi.com/releases/sdk/pulumi-v2.15.6-windows-x64.tar.gz...
Progressbar is not supported by the system
Download finished.
Unpacking archive at C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\@dev-thought\pulumi-npm\tools\pulumi.tar.gz...
C:\XXX\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\@dev-thought\pulumi-npm\tools\pulumi.tar.gz C:\XXXl\AppData\Roaming\npm\node_modules\@dev-thought\nx-deploy-it\node_modules\@dev-thought\pulumi-npm\tools
An error occurred while unpacking: Error: Unexpected end of data

**Comment by MitkoTschimev** [comment]
ok I created a beta version with other adjustments. the unzipping was using the progressbar too 👍 
To make it easier for you try following command

```
npx @dev-thought/pulumi-npm@1.5.3-beta.0 version
```

**Comment by zdenekmikel** [comment]
Still same error
1512 verbose stack Error: @dev-thought/pulumi-npm@1.5.3-beta.0 postinstall: `node src/install-pulumi`
1512 verbose stack Exit status 40
1512 verbose stack     at EventEmitter.<anonymous> (C:\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
1512 verbose stack     at EventEmitter.emit (events.js:200:13)
1512 verbose stack     at ChildProcess.<anonymous> (C:\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1512 verbose stack     at ChildProcess.emit (events.js:200:13)
1512 verbose stack     at maybeClose (internal/child_process.js:1021:16)
1512 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
1513 verbose pkgid @dev-thought/pulumi-npm@1.5.3-beta.0

**Comment by anhvun** [comment]
PR #7 should fix this, the problem was incorrect file-name and type handing for windows machines

**Comment by MitkoTschimev** [comment]
New version published -> 1.5.3 
Please try on your windows machines :)
